### ISSUE TITLE
Format nama file dengan jam

### ISSUE THREAD

**Issue by azizramdan** [musaamin/backup-mysql#1]
Saat ini format nama hanya berdasarkan tanggal `currentDate := time.Now().Format("20060102")` sehingga kesannya hanya bisa dilakukan backup sekali sehari. Sepertinya perlu ditambah jam juga sehingga nama filenya misal jadi `mydb-20060102_150405.sql.gz`

**Comment by musaamin** [comment]
sudah ditambahkan jam `currentDate := time.Now().Format("20060102_150405")`

terima kasih.
